### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by R0binT** [kinotto/geonames.js#1]
Hi,
I got an error when I try to fetch some data with the geoname.contryInfo({}) function.

Here is the error message:
`XMLHttpRequest cannot load http://api.geonames.org/countryInfoJSON?formatted=true&style=full&username=username&lang=en. The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:3000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

**Comment by kinotto** [comment]
Vg

**Comment by R0binT** [comment]
Hi,
thanks for your reply.
Actually I am using a valid username. I just changed it in the error message so like that I keep it not public.

About the http, I don't do anything specific. I just followed your readme. Maybe is it because I am on my localhost.

here is my code (I changed the username again but don't worry I use a valid one) : 
`import Geonames from 'geonames.js';
geonames = new Geonames({username: 'myUserName', lan: "en", encoding: 'JSON'});`

About the "withCredential" thing, I dunno what is it.

**Comment by kinotto** [comment]
Hi,

Are you using <a href="https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi">this</a> chrome plugin?  if yes this could cause the error because it forces the _Access-Control-Allow-Origin_ header to the wildcard '*'.

If not, please post the whole code,  since i cannot reproduce the problem it's very difficult to help you.

let me know.

**Comment by R0binT** [comment]
Hi,

Nope I am not using such plugin. I tried with an other browser and it doesn' t change anything.

I am actually developping in Meteor.JS

here is the code : 

`import Geonames from 'geonames.js';

Template.profileContainer.onCreated(function() {
  geonames = new Geonames({username: 'artax1200', lan: 'en', encoding: 'JSON'});
});

Template.profileContainer.onRendered(function() {
  geonames.countryInfo({})
  .then(function(countries){
    return geonames.children({geonameId: countries.geonames[0].geonameId})
  })
  .then(function(states){
    return geonames.children({geonameId: stateOrProvince.geonames[0].geonameId});
  })
  .then(function(regions){
    return geonames.children({geonameId: region.geonames[0].geonameId});
  })
  .then(function(cities){
    console.log(cities.geonames);
  })
  .catch(function(err){
  })
});`

**Comment by kinotto** [comment]
Are you using any session on your server? any login?

**Comment by R0binT** [comment]
I use it client side

**Comment by R0binT** [comment]
I succeed to make it work. In fact I was using it client side. But when I use it server side, it is working.

Sorry ^^

Thanks again for your reactivity and good job for the module :)

**Comment by kinotto** [comment]
Glad you did it ;)
