### ISSUE TITLE
Doesn't work with import es module

### ISSUE THREAD

**Issue by marticrespi** [kinotto/geonames.js#19]
Hi,

I'm building a node server with typescript, and I create a service that wraps a geoname client in its instance and it works if I use require option like my ts file below

````
const Geonames = require('geonames.js');

export class GeonamesService {

  private static _instance: GeonamesService;
  private geonamesClient;

  constructor() {
      this.geonamesClient = new Geonames({
        username: "username",
        lan: 'en',
        encoding: 'JSON'
      });
  }

  static get(): GeonamesService {
    if (!this._instance) {
      this._instance =  new GeonamesService();
    }
    return this._instance;
  }

  public async getCountries() {
      const countries = await this.geonamesClient.countryInfo({});
      console.log(countries);
      return countries;
  }


}


````

If I use 

````
import { Geonames } from 'geonames.js';
````

It throws an error when it's doing the new Geonames config..

````
'TypeError: geonames_js_1.Geonames is not a constructor'
````

Any idea what I'm doing wrong or it's a bug?

**Comment by pixelass** [comment]
it's not a named export so this should work:

```
import Geonames from 'geonames.js';
```

**Comment by kinotto** [comment]
hi @marticrespi 
sorry for the late reply,
the library is exported as a [default export](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#Syntax) not as a named export, as @pixelass  said

thank you  :)
