### ISSUE TITLE
401 response (user does not exist)

### ISSUE THREAD

**Issue by pixelass** [kinotto/geonames.js#21]
I am trying to use this library with a registered and activated user. Sadly I only get a 401 response.

http://api.geonames.org/findNearbyPlaceName?lat=47.3&lng=9&username=MY_USER_NAME (replace: MY_USER_NAME) returns 

```xml
<geonames>
<status message="user does not exist." value="10"/>
</geonames>
```

* The account has been activated
* I can login to the website with the account
* I can't make requests with the account

**Comment by kinotto** [comment]
Hi @pixelass ,
this is the response i'm getting (replacing MY_USER_NAME with a valid user)

```xml
<geonames>
<geoname>
<toponymName>Chrüzegg</toponymName>
<name>Chrüzegg</name>
<lat>47.2985</lat>
<lng>9.01488</lng>
<geonameId>7910950</geonameId>
<countryCode>CH</countryCode>
<countryName>Switzerland</countryName>
<fcl>P</fcl>
<fcode>PPLX</fcode>
<distance>1.1379</distance>
</geoname>
</geonames>
```

Most likely you're using an invalid user
If you keep getting the error i recommend asking in the geonames dedicated [forum](http://forum.geonames.org/gforum/forums/list.page;jsessionid=9E537E549E1003E51ACDC7717FB604FF), this library is just a wrapper around thieir REST webservices. in no way i have control over the responses :/

**Comment by pixelass** [comment]
Sorry I noticed this too. I'll ask in the forum

**Comment by kinotto** [comment]
thank you @pixelass , i hope you'll sort it out
