### ISSUE TITLE
GeocodeAddress doesn't exists

### ISSUE THREAD

**Issue by marticrespi** [kinotto/geonames.js#22]
Hi,

I'm using the library with typescript and my geonames client doesn't contains the geocodeAddress method.

http://api.geonames.org/geoCodeAddressJSON?q=Museumplein+6+amsterdam&username=demo

The library contains a `geocode` method but after send the request it returns a 404 error. 

````
'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /geocodeJSON was not found on this server.</p>
</body></html>
````

I think that the included method in the library must be updated to pointing at geoCodeAddress web service method. (/geoCodeAddressJSON)

Thanks!

**Comment by kinotto** [comment]
Hi @marticrespi ,
first of all thanks for using the library,
you're absolutely right, Geonames.org has updated[ the list of available services](https://www.geonames.org/export/ws-overview.html), i had to make a new release to add support to the latest ones which are: _address_, _geoCodeAddress_ and _streetNameLookup_
make sure to update the library to the latest version (3.0.2) and you should be able to use the geoCodeAddress service with no issue at all.

![img](https://i.imgur.com/dPYpyZP.gif)

Let me know :)

**Comment by marticrespi** [comment]
Perfect @kinotto , with the new version works as expected. Many thanks!
