### ISSUE TITLE
401 Error

### ISSUE THREAD

**Issue by AliSaeed090** [kinotto/geonames.js#33]
I created my account with my username. When I used that username it giving 401 error code

**Comment by kinotto** [comment]
hi @AliSaeed090 ,
http status code 401 means there's an underlying authentication issue, check that you're passing the correct username to the library

**Comment by MKoreo** [comment]
> I created my account with my username. When I used that username it giving 401 error code

Hey, I know it's been a while already. But perhaps for other users, this may be helpful.
Use following link: https://www.geonames.org/manageaccount (login and revisit if needed) and at the bottom click 'enable webservices'. They are not enabled by default.
