### ISSUE TITLE
Geonames is not a function

### ISSUE THREAD

**Issue by emerabet** [kinotto/geonames.js#49]
Hello,

following the indications of the readme I get the following error message. `TypeError: Geonames is not a function`
The lib usage changed ?

```
const { Geonames } = require('geonames.js')

this.geoNameClient = Geonames({
    username: 'xxxx',
    lan: 'en',
    encoding: 'JSON'
  });
```
Thanks!

**Comment by corepay** [comment]
I got it working by removing the {}

```const  Geonames = require('geonames.js')```
