### ISSUE TITLE
docs: potentially a note about importing into a TSX app?

### ISSUE THREAD

**Issue by piperchester** [kinotto/geonames.js#8]
Using a freshly installed TSX app through create-react-app, I tried importing the lib with

```js
import Geonames from 'geonames.js';
```

but I get the dreaded 

```
Could not find a declaration file for module 'geonames.js'. ... implicitly has an 'any' type.
```

Maybe we could add to the Readme about this to warn users?

**Comment by kinotto** [comment]
Hi @piperchester ,
i cannot reproduce the error now cause i don't have a working environment to test it, try just adding in your index.ts the module declaration

`declare module "geonames.js";`

and let me know if it works.

Thanks

**Comment by piperchester** [comment]
Warning disappeared :) is this something we may want to add to the Readme?

**Comment by kinotto** [comment]
yes fine, add a comment suggesting that instruction in a typscript environment. You can use the same  PR that you've already opened :)

**Comment by piperchester** [comment]
Done; added to #7
